### ISSUE TITLE
一些奇奇怪怪的问题

### ISSUE THREAD

**Issue by BraveRabbit8023** [B1lli/BillyGPT#7]
https://user-images.githubusercontent.com/59813847/230015493-49c927ff-a84b-4abd-9c4f-798a71e5d5b0.mp4

还有一个就是apikey不是自动更新或者次序调用吗，第一个api是寄的，即便添了新api也只调用第一个然后报错

**Comment by B1lli** [comment]
在V5.2.1的更新中，该问题已被修复
